spring:
  application:
    name: backend
  
  servlet:
    multipart:
      enabled: true
      max-file-size: -1 # 10MB
      max-request-size: -1 # 50MB
      file-size-threshold: -1 # 1MB

  profiles:
    active: dev

jwt:
  secret: "J!IO@EY@*#(j(@*#E(*@U#98@e@*@(&U#@Eeu!U@!@2uW)(!u98u1:"
